[package]
name          = "hid-io-core"
version       = "0.1.0-beta3"
authors       = ["Jacob Alexander <haata@kiibohd.com>"]
license       = "GPL-3.0-or-later"
description   = """
HID-IO is a host-side daemon for advanced HID devices.
"""

homepage      = "https://github.com/hid-io/hid-io-core"
repository    = "https://github.com/hid-io/hid-io-core"
documentation = "https://hid-io.github.io/hid-io/hid_io/"

edition       = "2018"
build         = "build.rs"
default-run   = "hid-io-core"


[features]
default = ["unicode"]
unicode = []


[build-dependencies]
built           = "0.3.0"
capnpc          = "^0.13"
rustc_version   = "0.2.3"


[dependencies]
bincode         = "^1.3"
capnp           = "^0.13"
capnp-rpc       = "^0.13"
clap            = "^2.33"
ctrlc           = "^3.1"
daemon          = "0.0.8"
lazy_static     = "^1.4"
flexi_logger    = "^0.16"
futures         = "^0.3"
futures-util    = "^0.3"
glob            = "^0.3"
libc            = "^0.2"
log             = "^0.4"
nanoid          = "0.2.0"
open            = "^1.4"
rand            = "^0.7"
rcgen           = "^0.5"
regex           = "^1.3"
rustls          = { version = "^0.18", features = ["dangerous_configuration"] }
serde           = "1.0.116"
stream-cancel   = "^0.6"
#tempfile        = "3.1.0"
tempfile        = { git = "https://github.com/haata/tempfile" } # Needed for world accessible patches
tokio           = { version = "^0.2", features = ["net", "rt-util", "tcp", "macros", "blocking", "sync", "stream", "time", "rt-core"]}
tokio-rustls    = ">=0.14.1"
tokio-util      = { version = "^0.3", features = ["compat"] }
webpki          = "^0.21"
windows-service = "0.1.0"


[dev-dependencies.cargo-husky]
version = "1"
features = ["prepush-hook", "run-cargo-fmt", "run-cargo-clippy", "run-cargo-test"]


[dependencies.hidapi]
git = "https://github.com/hid-io/hidapi-rs"
#version = "1.1.1"
default-features = false
features=["linux-static-hidraw"]


[target.'cfg(target_os = "linux")'.dependencies]
evdev-rs  = "^0.4"
udev      = "^0.5"
uhid-virt = "0.0.5"
xkbcommon = { version = "0.4.0", features = ["x11"] }
x11       = "2.18.2"


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["std", "winuser", "winnls"] }


[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.9.1"
core-graphics = "0.22.1"


[package.metadata.bundle]
identifier = "io.github.hid-io.hid-io-core"
category = "public.app-category.utilities"
icon = ["128x128.png"]
resources = ["hid-io-core.service"]


[profile.release]
panic = "abort" #windows
