[package]
name          = "hid-io-core"
version       = "0.1.0-beta2"
authors       = ["Jacob Alexander <haata@kiibohd.com>"]
license       = "GPL-3.0-or-later"
description   = """
HID-IO is a host-side daemon for advanced HID devices.
"""

homepage      = "https://github.com/hid-io/hid-io-core"
repository    = "https://github.com/hid-io/hid-io-core"
documentation = "https://hid-io.github.io/hid-io/hid_io/"

edition       = "2018"
build         = "build.rs"
default-run   = "hid-io"


[features]
default = ["unicode"]
unicode = []


[build-dependencies]
built           = "0.3.0"
capnpc          = "0.10.1"
rustc_version   = "0.2.3"


[dependencies]
bincode         = "1.0.1"
capnp           = "0.10.1"
capnp-rpc       = "0.10.0"
clap            = "2.32.0"
ctrlc           = "3.0"
daemon          = "0.0.8"
lazy_static     = "1.2.0"
flexi_logger    = "0.10.6"
futures         = "0.1.28"
hidapi          = "1.0.1"
log             = "0.4.3"
nanoid          = "0.2.0"
open            = "1.2.2"
rand            = "0.6.4"
rcgen           = "0.5.1"
rustls          = { version = "0.16.0", features = ["dangerous_configuration"] }
serde           = "1.0.71"
stream-cancel   = "0.4.4"
#tempfile        = "3.1.0"
tempfile        = { git = "https://github.com/haata/tempfile" } # Needed for world accessible patches
tokio           = { version = "0.1.22" }
tokio-core      = "^0.1"
tokio-rustls    = "0.10.2"
webpki          = "0.21.0"
windows-service = "0.1.0"


[dev-dependencies.cargo-husky]
version = "1"
features = ["prepush-hook", "run-cargo-fmt", "run-cargo-clippy", "run-cargo-test"]


[target.'cfg(target_os = "linux")'.dependencies]
xkbcommon = { version = "0.4.0", features = ["x11"] }
x11 = "2.18.1"


[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["std", "winuser", "winnls"] }


[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.6.4"
core-graphics = "0.17.3"


[package.metadata.bundle]
identifier = "io.github.hid-io.hid-io"
category = "public.app-category.utilities"
icon = ["128x128.png"]
resources = ["hid-io.service"]


[profile.release]
panic = "abort" #windows
