[package]
name          = "hid-io"
version       = "0.1.0-alpha"
authors       = ["Jacob Alexander <haata@kiibohd.com>"]
license       = "GPLv3"
description   = """
HID-IO is a host-side daemon for advanced HID devices.
"""

homepage      = "https://github.com/hid-io/hid-io"
repository    = "https://github.com/hid-io/hid-io"
documentation = "https://hid-io.github.io/hid_io/"

build         = "build.rs"
links = "X11"


[build-dependencies]
built         = "0.3.0"
capnpc        = "0.9.0"
rustc_version = "0.2.3"


[dependencies]
bincode      = "1.0.1"
capnp        = "0.9.0"
capnp-rpc    = "0.9.0"
clap         = "2.32.0"
env_logger   = "0.5.12"
hidapi       = "0.5.0"
log          = "0.4.3"
serde        = "1.0.71"
tokio        = "0.1"


[target.'cfg(target_os = "linux")'.dependencies]
xkbcommon = { version = "0.3.0", features = ["x11"] }
x11 = "2.18.1"


#[target.'cfg(windows)'.dependencies]
# TODO


#[target.'cfg(target_os = "macos")'.dependencies]
# TODO

