name: Rust Doc Deploy

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build libxtst-dev libclang-dev libevdev-dev llvm capnproto libudev-dev -y
      - name: cargo doc
        run: |
          cargo doc
      - name: GitHub Pages Deploy
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: target/doc
          GH_PAT: ${{ secrets.GH_PAT }}
