name: Rust Linux

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build libxtst-dev libclang-dev libevdev-dev llvm capnproto libudev-dev -y
      - uses: actions-rs/cargo@v1
        with:
          command: check

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build libxtst-dev libclang-dev libevdev-dev llvm capnproto libudev-dev -y
          python -m pip install --upgrade pip
      - uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Install pycapnp dependencies and run test
        run: |
          cd python
          python -m pip install cython
          CXXFLAGS=-fPIC CFLAGS=-fPIC python -m pip install -r requirements.txt
          python -m pytest -vvv

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build libxtst-dev libclang-dev libevdev-dev llvm capnproto libudev-dev -y
      - run: rustup component add clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
